// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store/filter.proto

package store // import "github.com/socketfunc/proto/store"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Filter_Comp int32

const (
	Filter_EQ     Filter_Comp = 0
	Filter_GT     Filter_Comp = 1
	Filter_GTE    Filter_Comp = 2
	Filter_LT     Filter_Comp = 3
	Filter_LTE    Filter_Comp = 4
	Filter_NE     Filter_Comp = 5
	Filter_EXISTS Filter_Comp = 6
)

var Filter_Comp_name = map[int32]string{
	0: "EQ",
	1: "GT",
	2: "GTE",
	3: "LT",
	4: "LTE",
	5: "NE",
	6: "EXISTS",
}
var Filter_Comp_value = map[string]int32{
	"EQ":     0,
	"GT":     1,
	"GTE":    2,
	"LT":     3,
	"LTE":    4,
	"NE":     5,
	"EXISTS": 6,
}

func (x Filter_Comp) String() string {
	return proto.EnumName(Filter_Comp_name, int32(x))
}
func (Filter_Comp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_filter_719920d3ffec2079, []int{0, 0}
}

type Filter struct {
	Comp                 Filter_Comp `protobuf:"varint,1,opt,name=comp,proto3,enum=store.Filter_Comp" json:"comp,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_filter_719920d3ffec2079, []int{0}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetComp() Filter_Comp {
	if m != nil {
		return m.Comp
	}
	return Filter_EQ
}

func (m *Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Filter)(nil), "store.Filter")
	proto.RegisterEnum("store.Filter_Comp", Filter_Comp_name, Filter_Comp_value)
}

func init() { proto.RegisterFile("store/filter.proto", fileDescriptor_filter_719920d3ffec2079) }

var fileDescriptor_filter_719920d3ffec2079 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0xce, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0x06, 0x60, 0xd3, 0x9b, 0x1b, 0xf1, 0x0c, 0x12, 0xce, 0x74, 0xc7, 0x5a, 0x41, 0x3a, 0x25,
	0xa0, 0x6f, 0xa0, 0xc6, 0x22, 0x14, 0xc1, 0x36, 0x83, 0xb8, 0xd9, 0x90, 0x6a, 0xd1, 0x34, 0xa5,
	0x4d, 0x5f, 0xc2, 0xa7, 0x96, 0x1c, 0xa7, 0xe4, 0x7c, 0xff, 0x3f, 0xfc, 0x80, 0x5b, 0x8a, 0xab,
	0xd7, 0xe3, 0xf4, 0x93, 0xfc, 0xaa, 0x96, 0x35, 0xa6, 0x88, 0x47, 0xb2, 0xea, 0x97, 0x81, 0x78,
	0x22, 0xc7, 0x1b, 0xe0, 0x2e, 0x86, 0xe5, 0xc4, 0x4a, 0x56, 0x5f, 0xde, 0xa2, 0xa2, 0x82, 0xfa,
	0x0f, 0xd5, 0x43, 0x0c, 0x4b, 0x47, 0x39, 0x22, 0xf0, 0xf9, 0x23, 0xf8, 0x53, 0x51, 0xb2, 0xfa,
	0xa2, 0xa3, 0x7f, 0xf5, 0x08, 0x3c, 0x37, 0x50, 0x40, 0x61, 0x5e, 0xe5, 0x59, 0x7e, 0x1b, 0x2b,
	0x19, 0x9e, 0xc3, 0xa1, 0xb1, 0x46, 0x16, 0x19, 0x5a, 0x2b, 0x0f, 0x19, 0x5a, 0x6b, 0x24, 0xcf,
	0xf0, 0x62, 0xe4, 0x11, 0x01, 0x84, 0x79, 0x7b, 0xee, 0x6d, 0x2f, 0xc5, 0xfd, 0xf5, 0xfb, 0xd5,
	0xe7, 0x94, 0xbe, 0xf6, 0x41, 0xb9, 0x18, 0xf4, 0x16, 0xdd, 0xb7, 0x4f, 0xe3, 0x3e, 0x3b, 0x4d,
	0x93, 0x35, 0x0d, 0x1a, 0x04, 0x1d, 0x77, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x7a, 0x9e,
	0xf1, 0xd5, 0x00, 0x00, 0x00,
}
